CREATE TABLE PRODUTOS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    MARCA VARCHAR(100),
    TIPO_PRODUTO VARCHAR(50),
    MEDIDA DECIMAL(10, 2),
    ALTURA DECIMAL(10, 2),
    PRECO DECIMAL(10, 2),
    COR VARCHAR(50),
    REVESTIMENTO VARCHAR(100),
    DENSIDADE VARCHAR(10),
    CARGA_SUPORTADA DECIMAL(10, 2),
    TRATAMENTOS_ESPECIAIS VARCHAR(100)
);