CREATE TABLE ITENS_PEDIDO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ID_PEDIDO BIGINT NOT NULL,
    ID_PRODUTO BIGINT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID),
    CONSTRAINT FK_ITEM_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);
